import { promises as fs } from 'node:fs';
import path from 'node:path';

function parseArgs(argv) {
  const args = {
    retentionDays: undefined,
    minKeep: undefined,
    dryRun: false,
    historyDir: 'history',
  };

  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === '--dry-run') {
      args.dryRun = true;
      continue;
    }
    if (a === '--retention-days') {
      args.retentionDays = Number(argv[i + 1]);
      i += 1;
      continue;
    }
    if (a === '--min-keep') {
      args.minKeep = Number(argv[i + 1]);
      i += 1;
      continue;
    }
    if (a === '--history-dir') {
      args.historyDir = argv[i + 1];
      i += 1;
      continue;
    }
    if (a === '--help' || a === '-h') {
      args.help = true;
      continue;
    }
  }

  return args;
}

function toInt(value, fallback) {
  const n = Number(value);
  return Number.isFinite(n) && n >= 0 ? Math.floor(n) : fallback;
}

async function readFileHeadUtf8(filePath, maxBytes) {
  const fh = await fs.open(filePath, 'r');
  try {
    const { size } = await fh.stat();
    const bytesToRead = Math.min(size, maxBytes);
    const buf = Buffer.alloc(bytesToRead);
    const { bytesRead } = await fh.read(buf, 0, bytesToRead, 0);
    return buf.subarray(0, bytesRead).toString('utf8');
  } finally {
    await fh.close();
  }
}

function extractMetaFromHead(headText) {
  // The data is generated by Playwright; the metadata we need appears early.
  // We intentionally use a lightweight regex scan instead of JSON.parse on huge files.
  const buildHrefMatch = headText.match(/"buildHref"\s*:\s*"([^"]+)"/);
  const buildHref = buildHrefMatch?.[1] ?? null;

  // Prefer committer time, fall back to author time.
  // Note: use [\s\S] to span newlines without enabling multiline flags.
  const committerTimeMatch = headText.match(
    /"gitCommit"\s*:\s*\{[\s\S]*?"committer"\s*:\s*\{[\s\S]*?"time"\s*:\s*(\d+)/
  );
  const authorTimeMatch = headText.match(
    /"gitCommit"\s*:\s*\{[\s\S]*?"author"\s*:\s*\{[\s\S]*?"time"\s*:\s*(\d+)/
  );

  const committerTimeMs = committerTimeMatch ? Number(committerTimeMatch[1]) : null;
  const authorTimeMs = authorTimeMatch ? Number(authorTimeMatch[1]) : null;

  return {
    buildHref,
    committerTimeMs: Number.isFinite(committerTimeMs) ? committerTimeMs : null,
    authorTimeMs: Number.isFinite(authorTimeMs) ? authorTimeMs : null,
  };
}

async function extractReportMeta(testResultsPath) {
  const HEAD_BYTES = 64 * 1024;
  try {
    const head = await readFileHeadUtf8(testResultsPath, HEAD_BYTES);
    const meta = extractMetaFromHead(head);
    if (meta.committerTimeMs || meta.authorTimeMs || meta.buildHref) return meta;
  } catch {
    // ignore and fall back below
  }

  // Fallback: stat only (cheap) when the file is missing/unreadable or format changed.
  return { buildHref: null, committerTimeMs: null, authorTimeMs: null };
}

function escapeHtml(s) {
  return s
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function renderHistoryIndex(entries) {
  // Keep styling consistent with the current repo page, but generate from scratch to avoid stale links.
  const listItems = entries
    .map((e) => {
      const buildNo = String(e.buildNumber);
      const reportHref = `./${buildNo}/index.html`;
      const title = `📊 建置 #${buildNo}`;

      const actionsLink = e.buildHref
        ? `<a href="${escapeHtml(e.buildHref)}" target="_blank" style='text-decoration: none; color: #28a745; font-size: 0.9em; margin-left: 10px;'>🔗 GitHub Actions</a>`
        : '';

      return (
        "<li style='margin: 10px 0; padding: 15px; border: 1px solid #ddd; border-radius: 8px; background-color: #f9f9f9; display: flex; justify-content: space-between; align-items: center;'>\n" +
        '  <div>\n' +
        `    <a href="${escapeHtml(reportHref)}" style='text-decoration: none; color: #0066cc; font-weight: bold; font-size: 1.1em;'>${escapeHtml(title)}</a>\n` +
        '  </div>\n' +
        `  <div>\n    ${actionsLink}\n  </div>\n` +
        '</li>'
      );
    })
    .join('\n');

  return (
    "<html><head><meta charset='UTF-8'><title>Playwright 測試報告歷史</title></head>\n" +
    "<body style='font-family: Arial, sans-serif; margin: 20px;'>\n" +
    "<h1>🎭 Playwright 測試報告歷史</h1>\n" +
    '<p>點擊下方連結查看各次測試報告</p>\n' +
    "<ul style='list-style-type: none; padding: 0;'>\n" +
    listItems +
    '\n</ul>\n' +
    '</body></html>\n'
  );
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    // eslint-disable-next-line no-console
    console.log(
      [
        'Usage: node scripts/cleanup-history.mjs [options]',
        '',
        'Options:',
        '  --retention-days <n>  Keep reports newer than N days (default: 7)',
        '  --min-keep <n>        Always keep at least the newest N reports (default: 20)',
        '  --history-dir <path>  History directory (default: history)',
        '  --dry-run             Do not delete or write files',
      ].join('\n')
    );
    return;
  }

  const retentionDays = toInt(
    args.retentionDays ?? process.env.RETENTION_DAYS,
    7
  );
  const minKeep = toInt(args.minKeep ?? process.env.MIN_KEEP, 20);
  const dryRun =
    args.dryRun ||
    String(process.env.DRY_RUN ?? '').toLowerCase() === 'true';

  const repoRoot = process.cwd();
  const historyDir = path.resolve(repoRoot, args.historyDir);
  const cutoffMs = Date.now() - retentionDays * 24 * 60 * 60 * 1000;

  const dirents = await fs.readdir(historyDir, { withFileTypes: true });
  const buildDirs = dirents
    .filter((d) => d.isDirectory() && /^\d+$/.test(d.name))
    .map((d) => d.name);

  const items = [];
  for (const buildName of buildDirs) {
    const buildNumber = Number(buildName);
    const dirPath = path.join(historyDir, buildName);
    const testResultsPath = path.join(dirPath, 'test-results.json');

    let stat = null;
    try {
      stat = await fs.stat(testResultsPath);
    } catch {
      stat = null;
    }

    const meta = stat ? await extractReportMeta(testResultsPath) : null;
    const metaTimeMs = meta?.committerTimeMs ?? meta?.authorTimeMs ?? null;
    const effectiveTimeMs = metaTimeMs ?? stat?.mtimeMs ?? 0;

    items.push({
      buildNumber,
      dirPath,
      testResultsPath,
      buildHref: meta?.buildHref ?? null,
      metaTimeMs,
      effectiveTimeMs,
      hasTestResults: Boolean(stat),
    });
  }

  // Sort newest first.
  items.sort((a, b) => {
    if (b.effectiveTimeMs !== a.effectiveTimeMs) return b.effectiveTimeMs - a.effectiveTimeMs;
    return b.buildNumber - a.buildNumber;
  });

  const keepByMinKeep = new Set(
    items.slice(0, minKeep).map((i) => i.buildNumber)
  );

  const keepByTime = new Set(
    items.filter((i) => i.effectiveTimeMs >= cutoffMs).map((i) => i.buildNumber)
  );

  const keepSet = new Set([...keepByMinKeep, ...keepByTime]);

  const toDelete = items.filter((i) => !keepSet.has(i.buildNumber));
  const kept = items.filter((i) => keepSet.has(i.buildNumber));

  // eslint-disable-next-line no-console
  console.log(
    [
      `history: ${path.relative(repoRoot, historyDir)}`,
      `retentionDays: ${retentionDays}`,
      `minKeep: ${minKeep}`,
      `cutoffMs: ${cutoffMs}`,
      `dryRun: ${dryRun}`,
      `foundBuilds: ${items.length}`,
      `kept: ${kept.length}`,
      `toDelete: ${toDelete.length}`,
    ].join('\n')
  );

  for (const it of toDelete) {
    const rel = path.relative(repoRoot, it.dirPath);
    // eslint-disable-next-line no-console
    console.log(`delete: ${rel}`);
    if (!dryRun) {
      await fs.rm(it.dirPath, { recursive: true, force: true });
    }
  }

  // Rebuild history/index.html from the remaining items.
  // Re-scan directory after deletion to reflect actual state.
  const direntsAfter = await fs.readdir(historyDir, { withFileTypes: true });
  const buildDirsAfter = direntsAfter
    .filter((d) => d.isDirectory() && /^\d+$/.test(d.name))
    .map((d) => d.name);

  const entries = [];
  for (const buildName of buildDirsAfter) {
    const buildNumber = Number(buildName);
    const testResultsPath = path.join(historyDir, buildName, 'test-results.json');
    let buildHref = null;
    try {
      await fs.stat(testResultsPath);
      const meta = await extractReportMeta(testResultsPath);
      buildHref = meta.buildHref;
    } catch {
      buildHref = null;
    }
    entries.push({ buildNumber, buildHref });
  }

  // Show newest first (by build number, which is the most intuitive in this repo).
  entries.sort((a, b) => b.buildNumber - a.buildNumber);

  const indexHtml = renderHistoryIndex(entries);
  const indexPath = path.join(historyDir, 'index.html');
  // eslint-disable-next-line no-console
  console.log(`write: ${path.relative(repoRoot, indexPath)} (${entries.length} entries)`);
  if (!dryRun) {
    await fs.writeFile(indexPath, indexHtml, 'utf8');
  }
}

await main();
